# Generated by Django 5.0.7 on 2024-07-15 16:15

import color.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hue', models.IntegerField(validators=[color.models.validate_hsv])),
                ('saturation', models.IntegerField(validators=[color.models.validate_hsv])),
                ('value', models.IntegerField(validators=[color.models.validate_hsv])),
            ],
        ),
    ]
