# Generated by Django 5.0.7 on 2024-07-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_hsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
